"""
Comprehensive validation: Finding model vs create_finding tool vs database schema
Identifies ALL field mismatches before deployment
"""
import os
import sys
from sqlalchemy import create_engine, inspect

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'api', 'src'))
from api.src import models

def validate_all_fields():
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        print("ERROR: DATABASE_URL not set")
        return False
    
    engine = create_engine(database_url)
    
    try:
        # 1. Get database schema columns
        print("\n" + "=" * 80)
        print("STEP 1: Analyzing Database Schema (findings table)")
        print("=" * 80)
        
        inspector = inspect(engine)
        db_columns = {}
        for col in inspector.get_columns('findings'):
            db_columns[col['name']] = {
                'type': str(col['type']),
                'nullable': col['nullable'],
                'default': col.get('default')
            }
        print(f"✅ Found {len(db_columns)} columns in database")
        
        # 2. Get SQLAlchemy model columns
        print("\n" + "=" * 80)
        print("STEP 2: Analyzing SQLAlchemy Model (models.Finding)")
        print("=" * 80)
        
        model_columns = {}
        for col_name, col_obj in models.Finding.__table__.columns.items():
            model_columns[col_name] = {
                'type': str(col_obj.type),
                'nullable': col_obj.nullable,
                'default': col_obj.default
            }
        print(f"✅ Found {len(model_columns)} columns in model")
        
        # 3. Fields set by create_finding code (from agentic_assistant.py line 2058-2076)
        print("\n" + "=" * 80)
        print("STEP 3: Analyzing create_finding Code")
        print("=" * 80)
        
        code_sets_fields = {
            'assessment_id',
            'project_id', 
            'agency_id',
            'control_id',
            'title',
            'description',
            'severity',
            'cvss_score',
            'category',
            'affected_asset',
            'reproduction_steps',
            'remediation_recommendation',
            'business_impact',
            'status',
            'discovery_date',
            'target_remediation_date',
            'created_by_user_id'
        }
        print(f"✅ Code sets {len(code_sets_fields)} fields explicitly")
        
        # 4. Find required fields (NOT NULL, no default)
        print("\n" + "=" * 80)
        print("STEP 4: Identifying REQUIRED Fields (NOT NULL, no auto-default)")
        print("=" * 80)
        
        auto_fields = {'id', 'created_at', 'updated_at'}  # Auto-generated by DB
        required_fields = []
        
        for col_name, col_info in db_columns.items():
            if col_name in auto_fields:
                continue
            if not col_info['nullable'] and col_info['default'] is None:
                required_fields.append(col_name)
        
        print(f"Found {len(required_fields)} required fields:\n")
        
        has_errors = False
        for field in sorted(required_fields):
            in_model = field in model_columns
            in_code = field in code_sets_fields
            
            status = "✅"
            if not in_model:
                status = "❌ NOT IN MODEL"
                has_errors = True
            elif not in_code:
                status = "❌ NOT SET BY CODE"
                has_errors = True
            
            print(f"  {field:30} | Model: {'✅' if in_model else '❌':3} | Code: {'✅' if in_code else '❌':3} | {status}")
        
        # 5. Check for extra fields in code not in model
        print("\n" + "=" * 80)
        print("STEP 5: Checking for Fields in Code but NOT in Model")
        print("=" * 80)
        
        extra_in_code = code_sets_fields - set(model_columns.keys())
        if extra_in_code:
            print("❌ These fields are set by code but DON'T EXIST in model:")
            for field in sorted(extra_in_code):
                print(f"   - {field}")
            has_errors = True
        else:
            print("✅ All code fields exist in model")
        
        # 6. Check for model/database mismatches
        print("\n" + "=" * 80)
        print("STEP 6: Checking Model vs Database Schema Consistency")
        print("=" * 80)
        
        model_only = set(model_columns.keys()) - set(db_columns.keys())
        db_only = set(db_columns.keys()) - set(model_columns.keys())
        
        if model_only:
            print("⚠️  Fields in MODEL but not in DATABASE:")
            for field in sorted(model_only):
                print(f"   - {field}")
            has_errors = True
        
        if db_only:
            print("⚠️  Fields in DATABASE but not in MODEL:")
            for field in sorted(db_only):
                print(f"   - {field}")
            has_errors = True
        
        if not model_only and not db_only:
            print("✅ Model and database schemas are in sync")
        
        # 7. Final summary
        print("\n" + "=" * 80)
        print("FINAL SUMMARY")
        print("=" * 80)
        
        missing_in_code = [f for f in required_fields if f not in code_sets_fields]
        
        print(f"\nDatabase columns:     {len(db_columns)}")
        print(f"Model columns:        {len(model_columns)}")
        print(f"Required fields:      {len(required_fields)}")
        print(f"Fields set by code:   {len(code_sets_fields)}")
        
        if missing_in_code:
            print(f"\n❌ CRITICAL ERROR: {len(missing_in_code)} required field(s) NOT set by code:")
            for field in sorted(missing_in_code):
                db_info = db_columns[field]
                print(f"\n   Field: {field}")
                print(f"   Type:  {db_info['type']}")
                print(f"   Nullable: {db_info['nullable']}")
                print(f"   → CODE MUST SET THIS FIELD!")
            print("\n⚠️  Finding creation will FAIL until these fields are set!")
            return False
        else:
            print(f"\n✅ SUCCESS: All required fields are properly set by code!")
            return True
    
    except Exception as e:
        print(f"\n❌ Validation failed with error: {e}")
        import traceback
        traceback.print_exc()
        return False
    finally:
        engine.dispose()

if __name__ == "__main__":
    print("\n" + "=" * 80)
    print("COMPREHENSIVE FINDING FIELD VALIDATION")
    print("=" * 80)
    
    success = validate_all_fields()
    
    print("\n" + "=" * 80)
    if success:
        print("✅ VALIDATION PASSED - Safe to deploy")
    else:
        print("❌ VALIDATION FAILED - DO NOT DEPLOY")
    print("=" * 80 + "\n")
    
    sys.exit(0 if success else 1)
